instalação da bibliotecas necessárias para o exercicio:
-> pip install yfinance

                                yfinance
-> É uma biblioteca de código aberto (open-source) para python desenvolvida
com um propósito muito claro: buscar dados financeiros e cotações de mercado
diretamente do Yahoo Finance de forma gratuita, rápida e estruturada. 

-> No universp da Análise de Dados e Finanças Quantitativas, ela se tornou
a ferramenta mais popular para substituir APIs pagas ou bibliotecas legadas
(como o antigo pandas_datareader).

                            O que ela faz na prática?
-> O grande trunfo da yfinance é que ela conversa com os servidores do Yahoo,
coleta dados brutos da internet e os converte automaticamente em um pandas.
DataFrame. Isso significa que, com apenas uma linha de código, você ganha
uma tabela perfeitamente limpa e pronta para análise. Ela permite que
você extraia informações como:

    Preços históricos de ações (abertura, fechamento, máximas, mínimas e volume
    de negociação).

    Dados de ativos globais e nacionais (como ações da B3, criptomoedas, fundos
    imobiliarios e indices como o ibovespa ^BVSP ou S&P500 ^GSPC)

    Informações fundamentalistas (balanço patrimonial, demonstrativo de
    resultados, dividendos distribuidos e desdobramentos de ações).

                    Como ela se organiza? (os principais componentes)

-> Para trabalhar com ela, você basicamente usará dois caminhos principais:

    1 - O método rápido em bloco (yfinance.download): Ideal para quando queremos só puxar o histórico de preços de um ou mais ativos de uma vez para montar
    um gráfico ou calcular rentabilidade.

    2. O objeto ticker (yfinance.Ticker): Ideal para quando precisamos fazer
    uma análise profunda da empresa especifica. Você cria um "objeto cliente"
    para aquela ação e ganha acesso a vários metodos internos.

                            Por que ela é tão usada?
-> Gratuita e sem necessidade de chave de API: Muitas plataformas de dados
financeiros exigem que você crie uma conta, cadastre cartão e use tokens/
chaves de acesso limitadas. A yfinance funciona direto, sem burocracia.

-> Integração nativa com ecossistema de dados: Como o retorno dela é um
DataFrame do pandas, você pode plugar os dados imediatamente no Matplotlib
ou Seaborn para plotar gráficos de linha das cotações, ou no Scikit-Learn
se estiver montando modelos de regressão para tentar prever tendências.

In [ ]:
# Import da biblioteca yfinance.
import yfinance

Visualizando cotações do ibovespa

In [ ]:
# Lista que irá conter o código das empresas que queremos acessar no Yahoo
# Finance
ativos = ["ITUB3.SA", "VALE3.SA", "PETR3.SA", "^BVSP"]

# Ira acessar o valor do indice 3 (empresa de indice 3)
ticker = ativos[3]

# Data inicial e data_final: Intervalo de datas que iremos acessar para coletar
# os dados.
data_inicial = "2026-01-01"

data_final = "2026-04-30"

# tabela_cotações: Ira conter as cotações extraidas da API da Yahoo

# download: Função da biblioteca yfinance que realiza as requisições
# a API e coleta os dados das cotações da empresa. A função recebe 
# como argumento:
# ticker: Código da empresa na API do yahoo finance.
# start: Recebe a data inicial do intervalo que queremos acessar.
# end: Recebe a data final do intervalo que queremos acessar
# Observação: A função retorna um Dataframe.
tabela_cotacoes = yfinance.download(ticker, start = data_inicial, end = data_final)

# Acessando as 10 primeiras linhas do Dataframe retornado
tabela_cotacoes.head(10)

[*********************100%***********************]  1 of 1 completed

Price          Close      High       Low      Open   Volume
Ticker         ^BVSP     ^BVSP     ^BVSP     ^BVSP    ^BVSP
2026-01-02  160539.0  161957.0  160059.0  161124.0  7459400
2026-01-05  161870.0  162166.0  160215.0  160542.0  7985200
2026-01-06  163664.0  164135.0  161870.0  161870.0  8412600
2026-01-07  161975.0  163661.0  161746.0  163661.0  8846600
2026-01-08  162937.0  162937.0  161748.0  161975.0  8607700
2026-01-09  163370.0  164263.0  162638.0  162938.0  8301300
2026-01-12  163150.0  163493.0  162277.0  163370.0  6896600
2026-01-13  161973.0  163146.0  161765.0  163146.0  9668600
2026-01-14  165146.0  165147.0  161974.0  161974.0  9928900
2026-01-15  165568.0  166070.0  164833.0  165180.0  9406500

Verificando as principais informações do dataframe utilizando a função info

In [21]:
tabela_cotacoes.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 80 entries, 2026-01-02 to 2026-04-29
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Close, ^BVSP)   80 non-null     float64
 1   (High, ^BVSP)    80 non-null     float64
 2   (Low, ^BVSP)     80 non-null     float64
 3   (Open, ^BVSP)    80 non-null     float64
 4   (Volume, ^BVSP)  80 non-null     int64
dtypes: float64(4), int64(1)
memory usage: 3.8 KB

Filtrando colunas

In [ ]:
# É possivel filtrar valores do dataframe através do nome das colunas.
close = tabela_cotacoes['Close']

# Ira mostrar os valores filtrados do DataFrame.
display(close)

Ticker         ^BVSP
2026-01-02  160539.0
2026-01-05  161870.0
2026-01-06  163664.0
2026-01-07  161975.0
2026-01-08  162937.0
...              ...
2026-04-23  191378.0
2026-04-24  190745.0
2026-04-27  189579.0
2026-04-28  188619.0
2026-04-29  184750.0

[80 rows x 1 columns]

Visualizando todas as cotações

In [ ]:
# Nesse caso, ao invés de passar um ativo especifico, vamos passar a lista
# inteira de ativos. 
todos_ativos = yfinance.download(ativos, start=data_inicial, end=data_final)

# Ira mostrar os valores do dataframe
display(todos_ativos)

[*********************100%***********************]  4 of 4 completed

Price           Close                        ...    Volume
Ticker       ITUB3.SA   PETR3.SA   VALE3.SA  ...  PETR3.SA  VALE3.SA    ^BVSP
2026-01-02  35.943691  31.906075  72.379997  ...  15637900  28418900  7459400
2026-01-05  36.547535  31.372662  73.120003  ...  15270700  24958100  7985200
2026-01-06  37.052399  30.770100  75.870003  ...  12059600  39536600  8412600
2026-01-07  36.329758  30.799734  76.320000  ...  11359800  41501600  8846600
2026-01-08  36.745518  31.570221  75.580002  ...   9513700  31894900  8607700
...               ...        ...        ...  ...       ...       ...      ...
2026-04-23  43.851685  52.750000  85.970001  ...  10415600  12637500  7763400
2026-04-24  44.301498  52.240002  85.870003  ...   8963300  11436400  7223800
2026-04-27  43.771721  52.419998  85.500000  ...   8445700   8656600  6663800
2026-04-28  43.861683  52.799999  84.389999  ...   8064700  13687500  7511500
2026-04-29  42.672176  54.470001  79.440002  ...  15662800  43296200  9054900

[80 rows x 20 columns]

In [ ]:
# Também é possivel filtrar as colunas logo após a requisição, basta filtrar
# os dados assim que a função download realizar a requisição a API. Dessa forma,
# a variável todos_ativos irá mostrar apenas a coluna filtrada
todos_ativos = yfinance.download(ativos, start=data_inicial, end=data_final)['Close']

# Impressão dos valores filtrados na requisição
display(todos_ativos)

[*********************100%***********************]  4 of 4 completed

Ticker       ITUB3.SA   PETR3.SA   VALE3.SA     ^BVSP
2026-01-02  35.943691  31.906075  72.379997  160539.0
2026-01-05  36.547535  31.372662  73.120003  161870.0
2026-01-06  37.052399  30.770100  75.870003  163664.0
2026-01-07  36.329758  30.799734  76.320000  161975.0
2026-01-08  36.745518  31.570221  75.580002  162937.0
...               ...        ...        ...       ...
2026-04-23  43.851685  52.750000  85.970001  191378.0
2026-04-24  44.301498  52.240002  85.870003  190745.0
2026-04-27  43.771721  52.419998  85.500000  189579.0
2026-04-28  43.861683  52.799999  84.389999  188619.0
2026-04-29  42.672176  54.470001  79.440002  184750.0

[80 rows x 4 columns]